### ISSUE TITLE
import error, can't use at all

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/text#325]
installed by pip

error for tensorflow 2.2.0, 2.3.0-rc.0, and 2.4.0
with CUDA 10.2 and 11.0 both

```
>>> import tensorflow_text as text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wmind/anaconda3/lib/python3.8/site-packages/tensorflow_text/__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics
  File "/home/wmind/anaconda3/lib/python3.8/site-packages/tensorflow_text/python/metrics/__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "/home/wmind/anaconda3/lib/python3.8/site-packages/tensorflow_text/python/metrics/text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
  File "/home/wmind/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/wmind/anaconda3/lib/python3.8/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
```

**Comment by broken** [comment]
If you built TF from source, you will need to do the same for TF Text. Note that you will need to update the version of TF that is downloaded in the WORKSPACE file.

**Comment by broken** [comment]
You are facing the same issue as #317. It has some added details that you may find helpful.

**Comment by broken** [comment]
We've update to work with tf 2.3.x and released 2.3.0-rc1. This should be resolved.

**Comment by sakinaljana** [comment]
Hi @broken, seems this problem still appear. I had a chance to build the latest version of TF: v2.3.0, TF-addons: v0.11.2, and TF-text: v2.3.0.

all the builds are success, but failed to import `tensorflow_text` with similar error like above:
```
NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringB5cxx11EPNS_15OpKernelContextEb
```

You can reproduce the builds using following dockerfile snippet
```
# Build Tensorflow
ARG TENSORFLOW_VERSION=v2.3.0
RUN git clone https://github.com/tensorflow/tensorflow.git \
        --branch ${TENSORFLOW_VERSION} \
        --single-branch \
    && cd tensorflow \
#    && ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 && LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH} tensorflow/tools/ci_build/builds/configured GPU \
    && LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH} tensorflow/tools/ci_build/builds/configured GPU \
        bazel build -c opt --copt=-msse3 --copt=-msse4.1 --copt=-msse4.2 \
            --copt=-mavx --copt=-mavx2 \
            --copt=-mfma \
            --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
            --config=cuda --action_env=LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH} \
            --verbose_failures \
            tensorflow/tools/pip_package:build_pip_package \
    && bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip \
    && pip --no-cache-dir install --upgrade /tmp/pip/tensorflow-*.whl \
    && cd ..



# Build Tensorflow Add-ons
ARG TENSORFLOW_ADDONS=v0.11.2
RUN git clone https://github.com/tensorflow/addons.git \
        --branch ${TENSORFLOW_ADDONS} \
        --single-branch \
    && cd addons \
    && LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH} python ./configure.py \
    && bazel build --enable_runfiles build_pip_pkg \
    && bazel-bin/build_pip_pkg artifacts \
    && pip --no-cache-dir install --upgrade artifacts/tensorflow_addons-*.whl \
    && cd ..



# Build Tensorflow Text
ARG TENSORFLOW_TEXT_VERSION=v2.3.0
RUN git clone https://github.com/tensorflow/text.git \
        --branch ${TENSORFLOW_TEXT_VERSION} \
        --single-branch \
        && cd text \
        && chmod -R 777 oss_scripts \
        && ./oss_scripts/run_build.sh \
        && pip --no-cache-dir install --upgrade tensorflow_text-*.whl \
        && cd ..
```

Interestingly, if i did re-install for tensorflow-text (same version) from official pypi (but still using the build version for tensorflow), it's working. Do you have any idea why? Thanks in advance!
