### ISSUE TITLE
2.4.0rc1 windows wheel broken due to some binary incompatibility (Op:WordpieceTokenizeWithOffsets fails on LookupInterface parameter check)

### ISSUE THREAD

**Issue by eugene-shnitko** [tensorflow/text#476]
Seems very similar to https://github.com/tensorflow/text/issues/272#issue-601267559

import tensorflow as tf
from tensorflow_text import BertTokenizer
tokenizer = BertTokenizer('./vocab.txt')
tokenizer.tokenize('Test')

Fails with InvalidArgumentError: Trying to access resource using the wrong type. Expected class tensorflow::lookup::LookupInterface got class tensorflow::lookup::LookupInterface [Op:WordpieceTokenizeWithOffsets]

Any workaround would be greatly appreciated.

`---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-c4bedffee365> in <module>
      2 from tensorflow_text import BertTokenizer
      3 tokenizer = BertTokenizer('./vocab.txt')
----> 4 tokenizer.tokenize('Test')

C:\Anaconda3\lib\site-packages\tensorflow_text\python\ops\bert_tokenizer.py in tokenize(self, text_input)
    224     """
    225     tokens = self._basic_tokenizer.tokenize(text_input)
--> 226     return self._wordpiece_tokenizer.tokenize(tokens)

C:\Anaconda3\lib\site-packages\tensorflow_text\python\ops\wordpiece_tokenizer.py in tokenize(self, input)
    119       of the `jth` token in `input[i1...iN]`
    120     """
--> 121     subword, _, _ = self.tokenize_with_offsets(input)
    122     return subword
    123 

C:\Anaconda3\lib\site-packages\tensorflow_text\python\ops\wordpiece_tokenizer.py in tokenize_with_offsets(self, input)
    175           tokens = ragged_tensor.RaggedTensor.from_tensor(
    176               tokens, ragged_rank=rank - 1)
--> 177         wordpieces, starts, ends = self.tokenize_with_offsets(
    178             tokens.flat_values)
    179         wordpieces = wordpieces.with_row_splits_dtype(tokens.row_splits.dtype)

C:\Anaconda3\lib\site-packages\tensorflow_text\python\ops\wordpiece_tokenizer.py in tokenize_with_offsets(self, input)
    193       # Tokenize the tokens into subwords
    194       values, row_splits, starts, ends = (
--> 195           gen_wordpiece_tokenizer.wordpiece_tokenize_with_offsets(
    196               input_values=tokens,
    197               vocab_lookup_table=self._vocab_lookup_table.resource_handle,

<string> in wordpiece_tokenize_with_offsets(input_values, vocab_lookup_table, suffix_indicator, max_bytes_per_word, use_unknown_token, unknown_token, max_chars_per_token, split_unknown_characters, output_row_partition_type, name)

C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in raise_from_not_ok_status(e, name)
   6860   message = e.message + (" name: " + name if name is not None else "")
   6861   # pylint: disable=protected-access
-> 6862   six.raise_from(core._status_to_exception(e.code, message), None)
   6863   # pylint: enable=protected-access
   6864 

C:\Anaconda3\lib\site-packages\six.py in raise_from(value, from_value)

InvalidArgumentError: Trying to access resource using the wrong type. Expected class tensorflow::lookup::LookupInterface got class tensorflow::lookup::LookupInterface [Op:WordpieceTokenizeWithOffsets]`

**Comment by edloper** [comment]
Could you please post a full stack trace from the error?

**Comment by SenHan-lionheart** [comment]
I have installed the tensorflow-gpu 2.4.0 and tensorflow-text, which works normal as the official document. I can load the preprocessor and the bert model, it does not work when i provided the sentence to the preprocessor as input and give the error like : 
"InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Trying to access resource using the wrong type. Expected class tensorflow::lookup::LookupInterface got class tensorflow::lookup::LookupInterface
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/map/RaggedFromVariant/RaggedTensorFromVariant/_56]]
  (1) Invalid argument:  Trying to access resource using the wrong type. Expected class tensorflow::lookup::LookupInterface got class tensorflow::lookup::LookupInterface
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_restored_function_body_57351]

Function call stack:
restored_function_body -> restored_function_body
"
######## Below is my code and the bolded line is which the invalidArgumentError is arising from #########
import tensorflow_text as text
import tensorflow_hub as hub
import tensorflow as tf

preprocessor = hub.KerasLayer(
    "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/1")
sentence = "this is a nice sentence."
**encoder_inputs = preprocessor([sentence])**

**Comment by SenHan-lionheart** [comment]
> Could you please post a full stack trace from the error?
i have met this problem too.
I have installed the tensorflow-gpu 2.4.0 and tensorflow-text, which works normal as the official document. I can load the preprocessor and the bert model, however, it does not work when i provided the sentence to the preprocessor as input and get the error like :
"InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: Trying to access resource using the wrong type. Expected class tensorflow::lookup::LookupInterface got class tensorflow::lookup::LookupInterface
[[{{node StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets}}]]
[[StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/map/RaggedFromVariant/RaggedTensorFromVariant/_56]]
(1) Invalid argument: Trying to access resource using the wrong type. Expected class tensorflow::lookup::LookupInterface got class tensorflow::lookup::LookupInterface
[[{{node StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_restored_function_body_57351]

Function call stack:
restored_function_body -> restored_function_body
"
######## Below is my code and the bolded line is which the invalidArgumentError is arising from #########
import tensorflow_text as text
import tensorflow_hub as hub
import tensorflow as tf

preprocessor = hub.KerasLayer(
"https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/1")
sentence = "this is a nice sentence."
encoder_inputs = preprocessor([sentence])

**Comment by broken** [comment]
Thanks; we just noticed this as well as we were bringing up the Windows CI tests. It appears to affect : BertTokenizer, WordpieceTokenizer, SplitMergeTokenizer, & SplitMergeFromLogitsTokenizer.

We are trying to get in a similar fix for Windows that was made for Mac to fix #272. This will be in core TF, so will only appear in nightly initially, but we are also in the process of bringing up our own nightly released package so there will be an avenue to have this resolved quickly.

I'll keep this thread updated with progress.

**Comment by broken** [comment]
Apologies for the delayed response, but this is now fixed in tf-nightly.

You may need to run tensorflow-text-nightly as well, as I believe TF's ABI has changed.

**Comment by Austout** [comment]
As a note, this also breaks the [Transformer tutorial for en to portuguese](https://www.tensorflow.org/tutorials/text/transformer)

**Comment by julianeraso** [comment]
Hello dear all, I already run tensorflow-text-nightly and the error is still the same. Could you please help me?

**Comment by BichengWang** [comment]
met same issue.

**Comment by Dormanator** [comment]
> Apologies for the delayed response, but this is now fixed in tf-nightly.
> 
> You may need to run tensorflow-text-nightly as well, as I believe TF's ABI has changed.

Using the nightly releases worked for me: 
```
pip install tf-nightly
pip install tensorflow-text-nightly
pip install tf-models-nightly
```

**Comment by klyuhang9** [comment]
> > Apologies for the delayed response, but this is now fixed in tf-nightly.
> > You may need to run tensorflow-text-nightly as well, as I believe TF's ABI has changed.
> 
> Using the nightly releases worked for me:
> 
> ```
> pip install tf-nightly
> pip install tensorflow-text-nightly
> pip install tf-models-nightly
> ```

Hi  @broken   After that, I meet new problem:

`Traceback (most recent call last):
  File "G:/project/BERT_TF/Test_01.py", line 8, in <module>
    import tensorflow_text as text
  File "E:\BERT_TF_nightly2\lib\site-packages\tensorflow_text\__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics
  File "E:\BERT_TF_nightly2\lib\site-packages\tensorflow_text\python\metrics\__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "E:\BERT_TF_nightly2\lib\site-packages\tensorflow_text\python\metrics\text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
  File "E:\BERT_TF_nightly2\lib\site-packages\tensorflow\python\framework\load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: E:\BERT_TF_nightly2\lib\site-packages\tensorflow_text\python\metrics\_text_similarity_metric_ops.so not found `

I don't know how to fix this problem, thanks for help.

**Comment by klyuhang9** [comment]
> > > Apologies for the delayed response, but this is now fixed in tf-nightly.
> > > You may need to run tensorflow-text-nightly as well, as I believe TF's ABI has changed.
> > 
> > 
> > Using the nightly releases worked for me:
> > ```
> > pip install tf-nightly
> > pip install tensorflow-text-nightly
> > pip install tf-models-nightly
> > ```
> 
> Hi @broken After that, I meet new problem:
> 
> `Traceback (most recent call last): File "G:/project/BERT_TF/Test_01.py", line 8, in <module> import tensorflow_text as text File "E:\BERT_TF_nightly2\lib\site-packages\tensorflow_text\__init__.py", line 21, in <module> from tensorflow_text.python import metrics File "E:\BERT_TF_nightly2\lib\site-packages\tensorflow_text\python\metrics\__init__.py", line 20, in <module> from tensorflow_text.python.metrics.text_similarity_metric_ops import * File "E:\BERT_TF_nightly2\lib\site-packages\tensorflow_text\python\metrics\text_similarity_metric_ops.py", line 28, in <module> gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so')) File "E:\BERT_TF_nightly2\lib\site-packages\tensorflow\python\framework\load_library.py", line 58, in load_op_library lib_handle = py_tf.TF_LoadLibrary(library_filename) tensorflow.python.framework.errors_impl.NotFoundError: E:\BERT_TF_nightly2\lib\site-packages\tensorflow_text\python\metrics\_text_similarity_metric_ops.so not found `
> 
> I don't know how to fix this problem, thanks for help.

My version as follow:
tf-nightly == 2.5.0dev20210204
tensorflow-text-nightly ==2.6.0dev20210502
tf-models-nightly ==2.4.0dev20210502
python == 3.8.6
as all. Thanks

**Comment by broken** [comment]
The minor versions between TF & TF Text need to match. So if you are using tensorflow-text-nightly ==2.6.0dev20210502, you should also at least use TF of that same minor version - 2.6.x. For nightly, I recommend using the exact same - 2.6.0dev20210502.

In the installation of the tensorflow-text package this is enforced. However, after some discussions with others, we decided not to have this same enforcement for the nightly package. The reasons being that there are no definitive version boundaries where TF could change their ABI (which is why I recommend using the exact same version above), and we concluded users using nightly are aware that they are on the bleeding edge and are willing to accept the risk of version mismatch.

ps. I recommend leaving comments on new or open issues. With this one closed already, it was likely that we would've missed it.

Best,
